Update Build Script

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -1,4 +1,28 @@
 #!/usr/bin/env bash
 set -e # halt script on error
 
+# skip if build is triggered by pull request
+if [ $TRAVIS_PULL_REQUEST == "true" ]; then
+  echo "this is PR, exiting"
+  exit 0
+fi
+
+# enable error reporting to the console
+set -e
+
+# cleanup "_site"
+rm -rf _site
+mkdir _site
+
+# clone remote repo to "_site"
+git clone https://${GH_TOKEN}@github.com/GradyHooker/esportskingdom.git --branch gh-pages _site
+
+# build with Jekyll into "_site"
 bundle exec jekyll build
+
+# push
+cd _site
+git config user.name "Travis CI Bot"
+git add --all
+git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
+git push --force origin gh-pages
